title: ctrWolfen
author: "Rinnegatamante"
version: 1.3
description: "CIA Manager"
long-description: "CIA manager that works up to firmware 10.3"
file: https://github.com/Repo3DS/ideal-enigma/releases/download/r1/ctrWolfen.tar.xz
filesize: 986896
file-md5: 310df5665b2536468ae1cf1450d0a6a4
