title: Rokoban
author: Zalo
version: 1.0
category: games
rating: E
description: "3D Sokoban clone"
file: https://github.com/Repo3DS/BrewRepo/releases/download/r1/Rokoban.zip
filesize: 3363694
file-md5: 2e07360603a77f3ec7cda7440a85a948
screenshots:
  - "http://i.imgur.com/9ymgfev.png"
  - "http://i.imgur.com/me2L2DY.png"
  - "http://i.imgur.com/7U9vYEO.png"
  - "http://i.imgur.com/hsaDQDT.png"
