title: 3DSBriscola
author: Rinnegatamante
version: 1.0
category: games
rating: E
description: "Italian card game"
file: https://github.com/Repo3DS/ideal-enigma/releases/download/r1/3DSBriscola.rar
filesize: 10593367
file-md5: 88d2307b60b70b94cd1947d0d4658979
