title: CHMM2
author: "Rinnegatamante"
version: 2.6
category: utilities
rating: E
description: "Custom Home Menu Manager"
file: https://github.com/Repo3DS/BrewRepo/releases/download/r1/CHMM2.tar.xz
filesize: 724936
file-md5: ec86443f6b403693932ae8935eb3cce6
