title: "Play Coin Setter"
author: MrCheeze
version: 1.0
category: games
rating: E
description: "Mo' Money, Mo' Problems"
file: https://github.com/Repo3DS/BrewRepo/releases/download/r1/PlaycoinSetter.tar.xz
filesize: 83760
file-md5: 699e3e3599ea573700b1209c9391161a
