title: WANT3D
author: Rinnegatamante
version: 1.2
description: "\"Wanted!\" minigame clone"
long-description: "\"Wanted!\" minigame clone from Super Mario 64 DS. You'll have 20 seconds from start, each error gives you -3 seconds and each correct face give you +5 seconds."
file: https://github.com/Repo3DS/ideal-enigma/releases/download/r1/WANT3D.tar.xz
filesize: 647712
file-md5: 27a991dcbae8dec188ac3177d05da694
