title: WANT3D
author: Rinnegatamante
version: 1.2
category: games
rating: E
description: "\"Wanted!\" minigame clone"
long-description: "\"Wanted!\" minigame clone from Super Mario 64 DS. You'll have 20 seconds from start, each error gives you -3 seconds and each correct face give you +5 seconds."
file: https://github.com/Repo3DS/BrewRepo/releases/download/r1/WANT3D.tar.xz
filesize: 647724
file-md5: 6e364f7d9e60c1a57e69b97234b0049f
