title: 3DSudoku
author: "Rinnegatamante"
version: 1.0
category: games
rating: E
description: "Sudoku game"
file: https://github.com/Repo3DS/BrewRepo/releases/download/r1/3DSudoku.tar.xz
filesize: 627116
file-md5: 718edd9c0031b9acd5fd939c9a13293f
