title: WhackMania
author: Zalo
version: 1.0
category: games
rating: E
description: "3D Whack-a-mole game"
file: https://github.com/Repo3DS/BrewRepo/releases/download/r1/WhackMania.tar.xz
filesize: 12342528
file-md5: 850b7da648aaf202bbf494252ba30849
screenshots:
  - "http://i.imgur.com/w0K9Oef.png"
  - "http://i.imgur.com/COL5wgj.png"
  - "http://i.imgur.com/gxOJdTd.png"
  - "http://i.imgur.com/aRcAIJi.png"
  - "http://i.imgur.com/4RMUkJK.png"
