title: WhackMania
author: Zalo
version: 1.0
description: "3D Whack-a-mole game"
file: https://github.com/Repo3DS/ideal-enigma/releases/download/r1/WhackMania.zip
filesize: 12511827
file-md5: 7bc7097910aa4c8f7e3662e3a5b9e4dd
